
name: 'Security Scan'

on:
  push:
    branches:
      - main
      - staging

jobs:
  conviso-ast:
    runs-on: ubuntu-latest
    container:
      image: convisoappsec/convisocli:beta
      env:
        CONVISO_API_KEY: '${{secrets.CONVISO_API_KEY}}'
        CONVISO_API_URL: 'https://api.convisoappsec.com/'
        CONVISO_COMPANY_ID: 443
    steps:
      - uses: actions/checkout@v5
      - name: Run AST
        run: conviso ast run --vulnerability-auto-close
